--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    name: server
  name: server
  namespace: yolo  
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      name: server
  template: 
    metadata:  
      labels: 
        name: server
    spec: 
      containers: 
        - 
          image: "mariogrdn/discovery-server-df:def"
          name: server
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: NotIn
                values:
                - agent
      restartPolicy: Always
