--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    name: yolo-tiny-remote
  name: yolo-tiny-remote
  namespace: yolo
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      name: yolo-tiny-remote
  template: 
    metadata: 
      labels: 
        name: yolo-tiny-remote
    spec: 
      containers: 
        - 
          name: yolo-tiny-remote
          env: 
            - 
              name: ROS_DOMAIN_ID
              value: "42"
            -
              name: DISCOVERY_SERVER_NAME
              value: server-service.yolo
            -
              name: YOLO_SERVICE_NAME
              value: yolo-service.yolo
            -
              name: YOLO_SERVICE_IP
              value: 0.0.0.0
            -
              name: FASTRTPS_DEFAULT_PROFILES_FILE
              value: /fastRTPS_profile/fastRTPS_profile_ds_yolo.xml  
          image: mariogrdn/minimal_yolo_tiny:defR
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - agent
