--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: yolo
  name: yolo-service
  namespace: yolo
spec: 
  ports: 
    - name: discovery
      port: 6000
      protocol: UDP
      targetPort: 6000
  selector: 
    name: yolo-tiny-remote
